'use strict';
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');
const crypto=require('node:crypto');
const {spawnSync}=require('node:child_process');
const {pathToFileURL}=require('node:url');
const {resolveRuntimeConfig,isPublicAnonKey}=require('../../src/lib/runtime-config');
const {createLocalApiHandler}=require('../../src/lib/local-api');
const {serveStaticFile}=require('../../src/lib/static-server');
const {cmdDeviceLogin}=require('../../src/commands/device-login');
const {cmdInit}=require('../../src/commands/init');
const ROOT=path.resolve(__dirname,'../..');
function check(value,message){if(!value)throw Error(message);}
function loopback(value){const u=new URL(value);check(u.protocol==='http:'&&u.hostname==='127.0.0.1'&&!u.username&&!u.password&&!u.search&&!u.hash&&u.pathname==='/','Acceptance targets must be explicit loopback origins');return u.origin;}
function publicKey(file){const mode=fs.statSync(file).mode&0o777;check((mode&0o077)===0,'Server environment must be private');const row=fs.readFileSync(file,'utf8').split(/\n/).find(s=>s.startsWith('ACCESS_ANON_KEY='));const key=row?.slice('ACCESS_ANON_KEY='.length);check(isPublicAnonKey(key),'Instance public key missing');return key;}
function plan(options){const a=loopback(options.a),c=loopback(options.c);check(a!==c,'Two independent origins required');return{targets:[a,c],operations:['real SDK signup/signin','actual CLI config and device authorization','real local auth/account proxy','A to C to A configuration and stale-credential rejection','standard Dashboard from private loopback'],applied:false};}
async function captureOutput(action){const oldOut=process.stdout.write,oldErr=process.stderr.write;let stdout='',stderr='';process.stdout.write=(chunk,...args)=>{stdout+=String(chunk);const cb=args.find(v=>typeof v==='function');cb?.();return true;};process.stderr.write=(chunk,...args)=>{stderr+=String(chunk);const cb=args.find(v=>typeof v==='function');cb?.();return true;};try{return{result:await action(()=>stdout),stdout,stderr};}finally{process.stdout.write=oldOut;process.stderr.write=oldErr;}}
function initializeProducer(home,tracker){
 const directory=path.join(home,'.codex/sessions/2026/10/08');fs.mkdirSync(directory,{recursive:true,mode:0o700});
 const id=crypto.randomUUID(),usage={input_tokens:333,cached_input_tokens:0,output_tokens:0,reasoning_output_tokens:0,total_tokens:333};
 const events=[{timestamp:'2026-10-08T12:00:00Z',type:'session_meta',payload:{id,cwd:path.join(home,'controlled-project')}},{timestamp:'2026-10-08T12:00:01Z',type:'turn_context',payload:{model:'gpt-6'}},{timestamp:'2026-10-08T12:00:02Z',type:'event_msg',payload:{type:'token_count',info:{last_token_usage:usage,total_token_usage:usage}}}];
 fs.writeFileSync(path.join(directory,'rollout-2026-10-08T12-00-00-'+id+'.jsonl'),events.map(x=>JSON.stringify(x)).join('\n')+'\n',{mode:0o600});
 const pref=path.join(tracker,'cloud-sync-pref.json'),saved=fs.readFileSync(pref);fs.writeFileSync(pref,'{"enabled":false}\n',{mode:0o600});
 const env={};for(const key of ['HOME','USER','LOGNAME','TMPDIR','LANG','LC_ALL','LC_CTYPE','PATH'])if(process.env[key]!==undefined)env[key]=process.env[key];env.DO_NOT_TRACK='1';
 let r;try{const code='require('+JSON.stringify(path.join(ROOT,'src/commands/sync.js'))+').cmdSync(["--auto"],'+JSON.stringify({home,trackerDataDir:tracker,scanSources:['codex']})+').catch(()=>{process.exitCode=1})';r=spawnSync(process.execPath,['-e',code],{cwd:ROOT,env,encoding:'utf8',timeout:60000});check(r.status===0,'Production parser initialization failed');}finally{fs.writeFileSync(pref,saved,{mode:0o600});}
 const queue=fs.readFileSync(path.join(tracker,'queue.jsonl'),'utf8');const rows=queue.trim().split(/\n/).filter(Boolean).map(x=>JSON.parse(x));check(rows.reduce((a,x)=>a+(x.total_tokens||0),0)===333,'Canonical private fixture differs');
 return{queue,parser_exit:r.status,no_cloud_upload:true,private_metadata_only:true};
}
async function startAcceptance(options){
 const scoped=plan(options);check(options.apply,'Use --apply to execute');const directory=path.resolve(options.directory);check(directory!==ROOT&&!directory.startsWith(ROOT+path.sep),'Use a private working directory outside the repository');fs.mkdirSync(directory,{recursive:true,mode:0o700});check((fs.statSync(directory).mode&0o077)===0,'Working directory must be private');check(!fs.existsSync(path.join(directory,'acceptance-state.json')),'Existing acceptance state requires inspection');
 const targets={A:{base:scoped.targets[0],anon:publicKey(options.aEnv)},C:{base:scoped.targets[1],anon:publicKey(options.cEnv)}};check(targets.A.anon!==targets.C.anon,'Fresh instances require independent public keys');const sdkPackage=path.join(ROOT,'dashboard/node_modules/@insforge/sdk');check(JSON.parse(fs.readFileSync(path.join(sdkPackage,'package.json'))).version==='1.4.5','SDK acceptance must use pinned 1.4.5');const sdk=await import(pathToFileURL(path.join(sdkPackage,'dist/index.mjs')).href);
 const previousFetch=globalThis.fetch;const trace=[];const allowed=new Set(scoped.targets);let localOrigin;globalThis.fetch=async(input,init)=>{const u=new URL(typeof input==='string'?input:input.url||input.href);check(allowed.has(u.origin)||u.origin===localOrigin,'Acceptance request escaped selected local targets');const start=performance.now();const r=await previousFetch(input,{...init,signal:init?.signal||AbortSignal.timeout(30000)});trace.push({origin:u.origin,path:u.pathname,method:init?.method||'GET',status:r.status,elapsed_ms:Number((performance.now()-start).toFixed(3))});return r;};
 const users={};for(const label of ['A','C']){const instance=targets[label];if(options.resumeSessions){const saved=options.resumeSessions.users[label];check(saved?.refreshToken&&saved?.id,'Actual session resume requires owner and refresh credential');const restoring=sdk.createClient({baseUrl:instance.base,anonKey:instance.anon,isServerMode:true,debug:false,retryCount:0});const response=await restoring.auth.refreshSession({refreshToken:saved.refreshToken});check(!response.error&&response.data?.user?.id===saved.id&&response.data?.accessToken&&response.data?.refreshToken,'Actual SDK session resume failed');const client=sdk.createClient({baseUrl:instance.base,anonKey:instance.anon,accessToken:response.data.accessToken,isServerMode:true,debug:false,retryCount:0});users[label]={id:saved.id,refreshToken:response.data.refreshToken,accessToken:response.data.accessToken,client};}else{const email='tt-switch-'+crypto.randomUUID()+'@example.invalid',password=crypto.randomBytes(24).toString('hex')+'aA1!';const client=sdk.createClient({baseUrl:instance.base,anonKey:instance.anon,isServerMode:true,debug:false,retryCount:0});const signup=await client.auth.signUp({email,password,name:'Local switching '+label});check(!signup.error&&signup.data?.user,'Actual signup failed');const login=await client.auth.signInWithPassword({email,password});check(!login.error&&login.data?.user?.id===signup.data.user.id,'Actual signin failed');users[label]={email,password,client,id:login.data.user.id,accessToken:login.data.accessToken};}}
 const home=options.resumeSessions?.home||path.join(directory,'client-home'),tracker=path.join(home,'.tokentracker/tracker');if(options.resumeSessions){check(fs.realpathSync(home).startsWith(fs.realpathSync(path.dirname(directory))+path.sep),'Resume home must remain inside owned private lab');check((fs.statSync(home).mode&0o077)===0,'Resume home must be private');}fs.mkdirSync(tracker,{recursive:true,mode:0o700});const queue=path.join(tracker,'queue.jsonl');const localRow={source:'codex',model:'gpt-6',hour_start:'2026-10-08T12:00:00Z',input_tokens:333,output_tokens:0,cached_input_tokens:0,cache_creation_input_tokens:0,reasoning_output_tokens:0,total_tokens:333,billable_total_tokens:333,total_cost_usd:0,conversation_count:1};let history=JSON.stringify(localRow)+'\n';const cursors='{"controlled":{"offset":99}}\n';if(!options.resumeSessions){fs.writeFileSync(queue,history,{mode:0o600});fs.writeFileSync(path.join(tracker,'cursors.json'),cursors,{mode:0o600});fs.writeFileSync(path.join(tracker,'cloud-sync-pref.json'),'{"enabled":true}\n',{mode:0o600});fs.writeFileSync(path.join(tracker,'config.json'),'{"providerPreference":"preserved","telemetry":false}\n',{mode:0o600});}
 if(options.resumeSessions){history=fs.readFileSync(queue,'utf8');const rows=history.trim().split(/\n/).filter(Boolean).map(x=>JSON.parse(x));check(rows.reduce((a,x)=>a+(x.total_tokens||0),0)===333,'Resumed canonical fixture missing');}else{const producer=initializeProducer(home,tracker);history=producer.queue;}
 const factorySource=createLocalApiHandler.toString();check(factorySource.includes('untrusted_auth_origin'),'Authentication origin guard must be loaded before acceptance');
 let selected='A';let handler;let server;let owned;let sentinels=Boolean(options.resumeSessions);const evidence={sdk:'1.4.5',real_auth:true,no_self_signed_jwt:true,private_working_directory:true,telemetry_disabled:true,producer_initialized_by_actual_parser:true,producer_warm_no_upload:true,provider_scan_sources:[],local_api_source_sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,'src/lib/local-api.js'))).digest('hex'),loaded_handler_factory_sha256:crypto.createHash('sha256').update(factorySource).digest('hex'),auth_origin_guard_loaded:true,checks:[],trace};const write=()=>fs.writeFileSync(path.join(directory,'acceptance-evidence.json'),JSON.stringify(evidence,null,2)+'\n',{mode:0o600});const configPath=path.join(tracker,'config.json');
 const getConfig=()=>JSON.parse(fs.readFileSync(configPath));const localSnapshot=()=>Object.fromEntries(['queue.jsonl','cursors.json'].map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(tracker,file))).digest('hex')]));const assertLocalData=before=>{check(JSON.stringify(localSnapshot())===JSON.stringify(before),'Instance change altered canonical local data');check(getConfig().providerPreference==='preserved','Local preference changed');check(getConfig().telemetry===false&&!getConfig().scanRoots,'Personal scanning/telemetry enabled');};
 async function select(label){const before=localSnapshot();check(label==='A'||label==='C','Unknown instance');const target=targets[label];const previousRuntime=resolveRuntimeConfig({config:getConfig(),env:{}});const changedInstance=previousRuntime.baseUrl!==target.base||previousRuntime.anonKey!==target.anon;const keyFile=path.join(directory,'public-'+label+'.txt');fs.writeFileSync(keyFile,target.anon,{mode:0o600});const previous=process.env.TOKENTRACKER_SKIP_FIRST_SYNC;process.env.TOKENTRACKER_SKIP_FIRST_SYNC='1';try{await captureOutput(()=>cmdInit(['--yes','--no-auth','--base-url',target.base,'--anon-key-file',keyFile,'--dashboard-url',localOrigin],{home}));}finally{if(previous===undefined)delete process.env.TOKENTRACKER_SKIP_FIRST_SYNC;else process.env.TOKENTRACKER_SKIP_FIRST_SYNC=previous;}selected=label;assertLocalData(before);const runtime=resolveRuntimeConfig({config:getConfig(),env:{}});check(runtime.baseUrl===target.base&&runtime.anonKey===target.anon,'CLI persisted configuration differs');if(changedInstance)check(!getConfig().deviceToken&&!getConfig().user_id,'Old CLI cloud identity retained');else if(getConfig().deviceToken)check(getConfig().deviceTokenBaseUrl===target.base&&getConfig().user_id===users[label].id,'Existing CLI identity belongs to a different owner');evidence.checks.push({operation:'CLI init selected '+label,persistent_target:true,first_sync_intentionally_disabled:true,local_data_preserved:true});write();return runtime;}
 async function deviceLogin(label){const target=targets[label];let approved=false;await captureOutput(async read=>cmdDeviceLogin(['--json'],{home,sleep:async()=>{if(approved)return;const text=read();const begin=text.indexOf('{'),end=text.lastIndexOf('}');check(begin>=0&&end>=begin,'CLI authorization output missing');const data=JSON.parse(text.slice(begin,end+1));const verified=new URL(data.verification_uri);check(verified.origin===localOrigin&&verified.pathname==='/device','CLI used a different dashboard');const grant=await users[label].client.functions.invoke('tokentracker-device-flow-grant',{method:'POST',body:{user_code:data.user_code}});check(!grant.error,'Actual CLI code grant failed');approved=true;}}));const config=getConfig();check(config.baseUrl===target.base&&config.deviceTokenBaseUrl===target.base&&config.user_id===users[label].id&&config.deviceToken,'CLI owner/device pairing failed');const body={buckets:[{...localRow,input_tokens:label==='A'?111:222,total_tokens:label==='A'?111:222,billable_total_tokens:label==='A'?111:222}]};const uploaded=await globalThis.fetch(target.base+'/functions/tokentracker-ingest',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+config.deviceToken,apikey:target.anon},body:JSON.stringify(body)});check(uploaded.status===200,'Actual CLI-issued device upload failed');evidence.checks.push({operation:'CLI device login '+label,real_grant_poll:true,real_ingest_http:uploaded.status});write();}
 async function proxySignIn(label){const target=targets[label],u=users[label];const r=await previousFetch(localOrigin+(u.password?'/api/auth/sessions':'/api/auth/refresh?client_type=mobile'),{method:'POST',headers:{'Content-Type':'application/json',apikey:target.anon,'x-tokentracker-instance':target.base},body:JSON.stringify(u.password?{email:u.email,password:u.password}:{refresh_token:u.refreshToken})});const b=await r.json();check(r.status===200&&b.user?.id===u.id,'Actual production auth proxy signin failed');u.proxyToken=b.accessToken;if(!u.password){u.refreshToken=b.refreshToken;u.client=sdk.createClient({baseUrl:target.base,anonKey:target.anon,accessToken:b.accessToken,isServerMode:true,debug:false,retryCount:0});}return{status:r.status,expected_owner:true};}
 async function summary(label){const r=await previousFetch(localOrigin+'/functions/tokentracker-usage-summary?account=1&from=2026-10-08&to=2026-10-08&tz=UTC');const b=await r.json();const base=label==='A'?111:222;let published=false;try{const offset=JSON.parse(fs.readFileSync(path.join(tracker,'queue.state.json'))).offset;const owner=JSON.parse(fs.readFileSync(path.join(tracker,'cloud-upload-owner.json')));published=offset>=Buffer.byteLength(history)&&owner.ownerId===users[label].id&&owner.baseUrl===targets[label].base;}catch{}const expected=(published?333:base)+(sentinels?base:0);check(r.status===200&&r.headers.get('x-tokentracker-account-view')==='1'&&b.totals?.total_tokens===expected,'Actual production account proxy differs');evidence.checks.push({operation:'account proxy '+label,http:r.status,actual_tokens:expected,cloud_view:true,local_queue_published:published});write();return{status:r.status,total_tokens:b.totals.total_tokens};}
 async function addSentinels(){for(const label of ['A','C']){const client=users[label].client;const issued=await client.functions.invoke('tokentracker-device-token-issue',{method:'POST',body:{device_name:'Controlled remote sentinel '+label,platform:'linux',machine_id:crypto.randomUUID()}});check(!issued.error&&issued.data?.token,'Remote sentinel device issue failed');const n=label==='A'?111:222;const r=await globalThis.fetch(targets[label].base+'/functions/tokentracker-ingest',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+issued.data.token,apikey:targets[label].anon},body:JSON.stringify({buckets:[{...localRow,input_tokens:n,total_tokens:n,billable_total_tokens:n}]})});check(r.status===200,'Remote sentinel upload failed');const read=await client.functions.invoke('tokentracker-account-summary?from=2026-10-08&to=2026-10-08&tz=UTC',{method:'GET'});check(!read.error&&read.data?.totals?.total_tokens===2*n,'Remote sentinel readback differs');evidence.checks.push({operation:'remote sentinel '+label,http:r.status,account_before_local_upload:2*n,actual_devices:2});}sentinels=true;write();}
 async function switchTo(label){const old=selected,oldToken=users[old].proxyToken;await select(label);await previousFetch(localOrigin+'/api/runtime-config.js');if(oldToken){const stale=await previousFetch(localOrigin+'/api/auth/sessions/current',{headers:{Authorization:'Bearer '+oldToken,apikey:targets[label].anon,'x-tokentracker-instance':targets[label].base}});check(stale.status===409,'Known previous-instance token was forwarded');evidence.checks.push({operation:old+' to '+label,previous_token_http:stale.status,local_data_preserved:true});write();}return{selected:label,old_credentials_cleared:true};}
 const allowedRoute=p=>p.startsWith('/api/auth/')||['/api/runtime-config.js','/api/local-auth','/functions/tokentracker-cloud-session','/functions/tokentracker-local-sync','/functions/tokentracker-cloud-sync-pref','/functions/tokentracker-usage-summary','/functions/tokentracker-usage-daily','/functions/tokentracker-usage-hourly','/functions/tokentracker-usage-monthly','/functions/tokentracker-usage-heatmap','/functions/tokentracker-usage-model-breakdown','/functions/tokentracker-model-pricing'].includes(p);
 handler=createLocalApiHandler({queuePath:queue,trackerDataDir:tracker,syncContext:{home,scanSources:[]},serverVersion:'controlled-selfhost-acceptance'});
 server=http.createServer(async(req,res)=>{const u=new URL(req.url,localOrigin||'http://127.0.0.1');try{if(u.pathname==='/ops/status'&&req.method==='GET'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({selected,ready:true,check_count:evidence.checks.length}));}if(u.pathname==='/ops/run'&&req.method==='POST'){check(!req.headers.origin,'Server-side operation only');let raw='';for await(const chunk of req){raw+=chunk;check(raw.length<4096,'Operation too large');}const data=JSON.parse(raw);let result;if(data.op==='switch')result=await switchTo(data.instance);else if(data.op==='signin')result=await proxySignIn(selected);else if(data.op==='summary')result=await summary(selected);else if(data.op==='device-login'){await deviceLogin(selected);result={done:true};}else throw Error('Unknown operation');res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(result));}if(allowedRoute(u.pathname)){if(await handler(req,res,u))return;}else if(u.pathname.startsWith('/api/')||u.pathname.startsWith('/functions/')){res.writeHead(501,{'Content-Type':'application/json'});return res.end('{"error":"unrelated_local_data_disabled_for_acceptance"}');}const dist=path.join(ROOT,'dashboard/dist');if(await serveStaticFile(dist,u.pathname==='/'?'/index.html':u.pathname,res,{localRuntimeConfig:true}))return;if(await serveStaticFile(dist,'/index.html',res,{localRuntimeConfig:true}))return;res.writeHead(404);res.end();}catch{res.writeHead(503,{'Content-Type':'application/json'});res.end('{"error":"controlled_acceptance_failed"}');}});
 await new Promise(resolve=>server.listen(options.port||8791,'127.0.0.1',resolve));localOrigin='http://127.0.0.1:'+server.address().port;owned={close:async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));globalThis.fetch=previousFetch;},origin:localOrigin,evidence,select,deviceLogin,proxySignIn,summary,switchTo};
 fs.writeFileSync(path.join(directory,'acceptance-state.json'),JSON.stringify({origin:localOrigin,targets:scoped.targets,credentials:'test passwords and JWT remain in process memory; normal CLI private config retains device token'},null,2)+'\n',{mode:0o600});if(options.resumeSessions){await select('A');await deviceLogin('A');await proxySignIn('A');await summary('A');evidence.checks.push({operation:'actual SDK owner-preserving session resume A/C',existing_sentinels_preserved:true,no_passwords_or_refresh_credentials_persisted:true});}else{await select('A');await deviceLogin('A');await proxySignIn('A');await summary('A');await switchTo('C');await deviceLogin('C');await proxySignIn('C');await summary('C');await switchTo('A');await deviceLogin('A');await proxySignIn('A');await summary('A');await addSentinels();}write();return owned;
}
function parse(argv){const o={};for(let i=0;i<argv.length;i++){const k=argv[i];if(k==='--apply')o.apply=true;else if(k==='--plan')continue;else if(['--a','--c','--a-env','--c-env','--directory','--port'].includes(k)){const key={'--a-env':'aEnv','--c-env':'cEnv'}[k]||k.slice(2);o[key]=argv[++i];}else throw Error('Unknown acceptance argument');}return o;}
if(require.main===module){(async()=>{const o=parse(process.argv.slice(2));if(!o.apply)return console.log(JSON.stringify(plan(o)));const owned=await startAcceptance(o);console.log(JSON.stringify({ready:true,origin:owned.origin,check_count:owned.evidence.checks.length,secrets_logged:false}));})().catch(()=>{console.error('Self-host acceptance failed; inspect private evidence, never dump credentials.');process.exitCode=1;});}
module.exports={loopback,publicKey,plan,parse,initializeProducer,startAcceptance};
