using System.Security.Cryptography;
using System.Text;
using TokenTrackerWin;
using Xunit;

namespace TokenTrackerWin.Tests;

/// <summary>
/// The updater executes what it downloads, so these cover the three outcomes the
/// release flow can produce: a matching digest (install), a mismatching one
/// (refuse + discard), and no SHA256SUMS entry at all (legacy release, the caller
/// keeps today's behaviour).
/// </summary>
public class UpdateIntegrityTests
{
    private const string SetupName = "TokenTracker-Setup.exe";

    private static string HexOf(byte[] bytes)
        => Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();

    private static string WriteTempFile(byte[] contents)
    {
        var path = Path.Combine(Path.GetTempPath(), $"tt-integrity-{Guid.NewGuid():N}.bin");
        File.WriteAllBytes(path, contents);
        return path;
    }

    [Fact]
    public async Task MatchingDigestVerifiesTheDownloadedFile()
    {
        var payload = Encoding.UTF8.GetBytes("pretend installer bytes");
        var path = WriteTempFile(payload);
        try
        {
            var sums = $"{HexOf(payload)}  {SetupName}\n";
            var expected = UpdateIntegrity.FindDigest(sums, SetupName);

            Assert.NotNull(expected);
            var actual = await UpdateIntegrity.ComputeSha256Async(path);
            Assert.True(UpdateIntegrity.Matches(expected, actual));
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public async Task MismatchingDigestIsRejected()
    {
        // Same length, different bytes: exactly the case the existing expectedSize
        // check cannot catch (a resumed download stitched together wrong).
        var published = Encoding.UTF8.GetBytes("pretend installer bytes");
        var corrupted = Encoding.UTF8.GetBytes("pretend 1nstaller bytes");
        Assert.Equal(published.Length, corrupted.Length);

        var path = WriteTempFile(corrupted);
        try
        {
            var sums = $"{HexOf(published)}  {SetupName}\n";
            var expected = UpdateIntegrity.FindDigest(sums, SetupName);
            var actual = await UpdateIntegrity.ComputeSha256Async(path);

            Assert.NotNull(expected);
            Assert.False(UpdateIntegrity.Matches(expected, actual));
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void MissingChecksumEntryReturnsNullRatherThanFailing()
    {
        // A SHA256SUMS that lists other assets but not ours, plus the empty/absent
        // body a legacy release yields. All must read as "no checksum published".
        var otherAssets =
            $"{new string('a', 64)}  TokenTrackerBar.dmg\n" +
            $"{new string('b', 64)}  TokenTracker-linux-x86_64.deb\n";

        Assert.Null(UpdateIntegrity.FindDigest(otherAssets, SetupName));
        Assert.Null(UpdateIntegrity.FindDigest("", SetupName));
        Assert.Null(UpdateIntegrity.FindDigest(null, SetupName));
    }

    [Fact]
    public void ParsesRealSha256SumOutputShapes()
    {
        var digest = new string('c', 64);

        // Text mode (two spaces), binary mode ('*'), CRLF, comments and blanks.
        var body =
            "# generated by the release workflow\r\n" +
            "\r\n" +
            $"{new string('d', 64)}  TokenTrackerBar.dmg\r\n" +
            $"{digest} *{SetupName}\r\n";

        Assert.Equal(digest, UpdateIntegrity.FindDigest(body, SetupName));
        // Hex casing carries no meaning.
        Assert.Equal(digest, UpdateIntegrity.FindDigest($"{digest.ToUpperInvariant()}  {SetupName}", SetupName));
    }

    [Fact]
    public void MalformedDigestsAreNeverAccepted()
    {
        Assert.Null(UpdateIntegrity.FindDigest($"notahash  {SetupName}", SetupName));
        Assert.Null(UpdateIntegrity.FindDigest($"{new string('e', 63)}  {SetupName}", SetupName));
        Assert.Null(UpdateIntegrity.FindDigest($"{new string('z', 64)}  {SetupName}", SetupName));

        // Matches() must not treat "no digest" as "everything matches".
        Assert.False(UpdateIntegrity.Matches(null, new string('f', 64)));
        Assert.False(UpdateIntegrity.Matches("", ""));
    }
}
